
services:
  trino:
    image: trinodb/trino:latest
    container_name: trino3
    ports:
      - "8086:8080"
    volumes:
      - "./catalog:/etc/trino/catalog"
      - "./trino-plugins/trino-openapi-1.73:/usr/lib/trino/plugin/openapi"
      - "./openapi-spec.yaml:/etc/trino/openapi-spec.yaml"
      - "./post-init.sh:/tmp/post-init.sh"
      - "./post-init.sql:/tmp/post-init.sql"
    command: ["/bin/bash", "/tmp/post-init.sh"]  
    networks:
      - trino_setup  

networks:
  trino_setup:
    name: trino_setup
